[project]
name = "multicast-standard"
authors = ["Multicast Governance Team"]
description = "A standardized, flexible governance contract for decentralized decision-making"
telemetry = false
requirements = []
[contracts.multicast-governance]
path = "contracts/multicast-governance.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
